name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Sauerkartoffel42
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          color_snake: "#00FF7F"
          color_dots: "#161B22,#30363D,#484F58,#6E7681,#C9D1D9" # GitHub dark theme shades

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
